[workspace]
members = ["android/rust", "demo", "native"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
eframe = { version = "0.31", features = ["wgpu", "android-game-activity"] }
egui = "0.31"
