[package]
name = "android"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
log = "0.4"
android_logger = "0.14"
eframe.workspace = true
egui-winit = "0.30"
core = { path = "../../core" }

[lib]
name = "main"
crate-type = ["cdylib"]
