[package]
name = "demo_native"
version.workspace = true
edition = "2021"
publish = false
default-run = "demo_native"

[dependencies]
core = { path = "../core" }
eframe.workspace = true
env_logger = "0.11"
